services:
  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    container_name: proxy
    ports:
      - 80:80
    depends_on:
      - fridge-api

  fridge-api:
    container_name: fridge-api
    build:
      context: wtfridge
      target: builder
    secrets:
      - serviceKey

secrets:
  serviceKey:
    file: ./secrets/live-firebase-serviceKey.json

  
  # goals-api:
  #   build:
  #     context: wtgoals
  #     target: builder

  # frontend:
  #   build:
  #     context: dadcad
  #   container_name: frontend