services:
  proxy:
    container_name: proxy
    image: proxy:local
    build:
      context: proxy
      target: builder
    ports:
      - 80:80
    depends_on:
      - fridge-api

  fridge-api:
    container_name: fridge-api
    image: fridge-api:local
    build:
      context: wtfridge
      target: builder
    secrets:
      - serviceKey

  finance-api:
    container_name: finance-api
    image: finance-api:local
    build: 
      context: wtfinance
      target: builder
    secrets:
      - googleSheets

secrets:
  serviceKey:
    file: ./secrets/firebase-serviceKey.json
  googleSheets:
    file: ./secrets/gsheets-serviceKey.json

  
  # goals-api:
  #   build:
  #     context: wtgoals
  #     target: builder

  # frontend:
  #   build:
  #     context: dadcad
  #   container_name: frontend